version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@6.14.0
  aws-ecs: circleci/aws-ecs@01.4.0
  aws-code-deploy: circleci/aws-code-deploy@1.0.1
  aws-cli: circleci/aws-cli@1.3.1

jobs:
  aws-cli-deploy:
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup:
          profile-name: circle-ci
      - run: aws deploy create-deployment --application-name AppECS-flask-app-cluster-ss-blue-green --deployment-group-name DgpECS-flask-app-cluster-ss-blue-green --revision revisionType=S3,s3Location="{bucket=support-service-codedeploy,key=appspec.yaml,bundleType=yaml}”


workflows:
  build-and-deploy:
    jobs:
      - aws-ecr/build-and-push-image:
          repo: "${AWS_ECR_REPO}"
          dockerfile: Dockerfile.ecr
      - aws-cli-deploy:
          requires:
            - aws-ecr/build-and-push-image         