version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@6.14.0
  aws-ecs: circleci/aws-ecs@01.4.0

workflows:
  build-and-deploy:
    jobs:
      - aws-ecr/build-and-push-image:
          repo: "${AWS_ECR_REPO}"
          path: .
      # - aws-ecs/deploy-service-update:
      #     requires:
      #       - aws-ecr/build-and-push-image
      #     family: "${AWS_TASK_DEFINITION}"
      #     service-name: "${AWS_SERVICE_NAME}"
      #     cluster-name: "${AWS_ECS_CLUSTER_ARN}"
      #     force-new-deployment: true
