version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@6.14.0
  aws-ecs: circleci/aws-ecs@01.4.0
  aws-code-deploy: circleci/aws-code-deploy@1.0.1

workflows:
  build-and-deploy:
    jobs:
      - aws-ecr/build-and-push-image:
          repo: "${AWS_ECR_REPO}"
          dockerfile: Dockerfile.ecr
      - aws-code-deploy/deploy:
          requires:
            - aws-ecr/build-and-push-image
          application-name: AppECS-flask-app-cluster-ss-blue-green
          bundle-bucket: support-service-codedeploy
          bundle-key: appspec.yml
          bundle-type: yaml
          deployment-group: DgpECS-flask-app-cluster-ss-blue-green
          service-role-arn: arn:aws:iam::955116512041:role/ecsCodeDeployRole